//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusInfo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SureshgowdEntities : DbContext
    {
        public SureshgowdEntities()
            : base("name=SureshgowdEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BusInfo> BusInfoes { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<FootBallLeague> FootBallLeagues { get; set; }
        public virtual DbSet<Bus_View> Bus_View { get; set; }
    
        public virtual ObjectResult<Football_Result> Football()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Football_Result>("Football");
        }
    
        public virtual ObjectResult<sp_BusInfo_Result> sp_BusInfo()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_BusInfo_Result>("sp_BusInfo");
        }
    
        public virtual ObjectResult<sp_Employee_Result> sp_Employee()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Employee_Result>("sp_Employee");
        }
    }
}
